services:
  api-ecomerce:
    container_name: api-ecomerce
    build: .
    ports:
      - "80:80"
    links:
      - sql-server-azure
  sql-server-azure:
    container_name: sql-server-azure
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: MyPassword123#
      ACCEPT_EULA: "Y"
    volumes:
      - ./sql:/var/opt/mssql
